name: Hello World Training Workflow

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User and checkout
      - run: ls -l
      - uses: actions/checkout@v2
      - run: ls -l
